release:
    name: Create GitHub Release
    needs: build
    if: success()
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v6
        with:
          # Download only our package binaries
          pattern: nlbw2collectd-binaries-*
          path: artifacts
          merge-multiple: true

      - name: Prepare Assets
        run: |
          mkdir -p release-assets
          find artifacts -name "nlbw2collectd*.ipk" -exec cp {} release-assets/ \;
          find artifacts -name "nlbw2collectd*.apk" -exec cp {} release-assets/ \;
          ls -R release-assets/

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          # List of files to upload
          artifacts: "release-assets/*"
          # Use the tag name as the release tag and title
          tag: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          # Recommended: Allow updating the release if the tag is re-pushed
          allowUpdates: true
          # Authentication
          token: ${{ secrets.GITHUB_TOKEN }}
